var annotated =
[
    [ "vg", null, [
      [ "core", null, [
        [ "Application", "classvg_1_1core_1_1_application.html", "classvg_1_1core_1_1_application" ],
        [ "Asset", "classvg_1_1core_1_1_asset.html", "classvg_1_1core_1_1_asset" ],
        [ "AssetManager", "classvg_1_1core_1_1_asset_manager.html", "classvg_1_1core_1_1_asset_manager" ],
        [ "FileManager", "classvg_1_1core_1_1_file_manager.html", "classvg_1_1core_1_1_file_manager" ]
      ] ],
      [ "graphics", null, [
        [ "Buffer", "classvg_1_1graphics_1_1_buffer.html", "classvg_1_1graphics_1_1_buffer" ],
        [ "Camera", "classvg_1_1graphics_1_1_camera.html", "classvg_1_1graphics_1_1_camera" ],
        [ "Character", "classvg_1_1graphics_1_1_character.html", "classvg_1_1graphics_1_1_character" ],
        [ "Font", "classvg_1_1graphics_1_1_font.html", "classvg_1_1graphics_1_1_font" ],
        [ "Graphics", "classvg_1_1graphics_1_1_graphics.html", "classvg_1_1graphics_1_1_graphics" ],
        [ "GraphicsContext", "classvg_1_1graphics_1_1_graphics_context.html", "classvg_1_1graphics_1_1_graphics_context" ],
        [ "IndexBuffer", "classvg_1_1graphics_1_1_index_buffer.html", "classvg_1_1graphics_1_1_index_buffer" ],
        [ "Screen", "classvg_1_1graphics_1_1_screen.html", "classvg_1_1graphics_1_1_screen" ],
        [ "Shader", "classvg_1_1graphics_1_1_shader.html", "classvg_1_1graphics_1_1_shader" ],
        [ "Texture", "classvg_1_1graphics_1_1_texture.html", "classvg_1_1graphics_1_1_texture" ],
        [ "TextureAtlas", "classvg_1_1graphics_1_1_texture_atlas.html", "classvg_1_1graphics_1_1_texture_atlas" ],
        [ "VertexBuffer", "classvg_1_1graphics_1_1_vertex_buffer.html", "classvg_1_1graphics_1_1_vertex_buffer" ],
        [ "VertexElement", "structvg_1_1graphics_1_1_vertex_element.html", "structvg_1_1graphics_1_1_vertex_element" ]
      ] ],
      [ "input", "namespacevg_1_1input.html", "namespacevg_1_1input" ],
      [ "sound", null, [
        [ "AudioManager", "classvg_1_1sound_1_1_audio_manager.html", "classvg_1_1sound_1_1_audio_manager" ],
        [ "SFXMapping", "classvg_1_1sound_1_1_s_f_x_mapping.html", "classvg_1_1sound_1_1_s_f_x_mapping" ],
        [ "Sound", "classvg_1_1sound_1_1_sound.html", "classvg_1_1sound_1_1_sound" ],
        [ "SoundEffect", "classvg_1_1sound_1_1_sound_effect.html", "classvg_1_1sound_1_1_sound_effect" ],
        [ "SoundEffectData", "structvg_1_1sound_1_1_sound_effect_data.html", "structvg_1_1sound_1_1_sound_effect_data" ]
      ] ],
      [ "AnimationComponent", "classvg_1_1_animation_component.html", "classvg_1_1_animation_component" ],
      [ "AnimationSystem", "classvg_1_1_animation_system.html", "classvg_1_1_animation_system" ],
      [ "BaseClass", "classvg_1_1_base_class.html", "classvg_1_1_base_class" ],
      [ "Color", "classvg_1_1_color.html", "classvg_1_1_color" ],
      [ "Component", "classvg_1_1_component.html", "classvg_1_1_component" ],
      [ "ContactListener", "classvg_1_1_contact_listener.html", null ],
      [ "DeleteSystem", "classvg_1_1_delete_system.html", "classvg_1_1_delete_system" ],
      [ "Game", "classvg_1_1_game.html", "classvg_1_1_game" ],
      [ "GameObject", "classvg_1_1_game_object.html", "classvg_1_1_game_object" ],
      [ "Joint", "classvg_1_1_joint.html", "classvg_1_1_joint" ],
      [ "Math", "classvg_1_1_math.html", null ],
      [ "PhysicsComponent", "classvg_1_1_physics_component.html", "classvg_1_1_physics_component" ],
      [ "PhysicsSystem", "classvg_1_1_physics_system.html", "classvg_1_1_physics_system" ],
      [ "Random", "classvg_1_1_random.html", null ],
      [ "RenderComponent", "classvg_1_1_render_component.html", "classvg_1_1_render_component" ],
      [ "RenderSystem", "classvg_1_1_render_system.html", "classvg_1_1_render_system" ],
      [ "Scene", "classvg_1_1_scene.html", "classvg_1_1_scene" ],
      [ "SceneManager", "classvg_1_1_scene_manager.html", "classvg_1_1_scene_manager" ],
      [ "System", "classvg_1_1_system.html", "classvg_1_1_system" ],
      [ "SystemManager", "classvg_1_1_system_manager.html", "classvg_1_1_system_manager" ],
      [ "TextComponent", "classvg_1_1_text_component.html", "classvg_1_1_text_component" ],
      [ "Timer", "classvg_1_1_timer.html", "classvg_1_1_timer" ],
      [ "TransformComponent", "classvg_1_1_transform_component.html", "classvg_1_1_transform_component" ],
      [ "Vec2f", "classvg_1_1_vec2f.html", "classvg_1_1_vec2f" ]
    ] ],
    [ "android_app", "structandroid__app.html", "structandroid__app" ],
    [ "android_poll_source", "structandroid__poll__source.html", "structandroid__poll__source" ],
    [ "network", "classnetwork.html", "classnetwork" ],
    [ "SLAndroidConfigurationItf_", "struct_s_l_android_configuration_itf__.html", "struct_s_l_android_configuration_itf__" ],
    [ "SLAndroidEffectCapabilitiesItf_", "struct_s_l_android_effect_capabilities_itf__.html", "struct_s_l_android_effect_capabilities_itf__" ],
    [ "SLAndroidEffectItf_", "struct_s_l_android_effect_itf__.html", "struct_s_l_android_effect_itf__" ],
    [ "SLAndroidEffectSendItf_", "struct_s_l_android_effect_send_itf__.html", "struct_s_l_android_effect_send_itf__" ],
    [ "SLAndroidSimpleBufferQueueItf_", "struct_s_l_android_simple_buffer_queue_itf__.html", "struct_s_l_android_simple_buffer_queue_itf__" ],
    [ "SLAndroidSimpleBufferQueueState_", "struct_s_l_android_simple_buffer_queue_state__.html", "struct_s_l_android_simple_buffer_queue_state__" ],
    [ "SLDataLocator_AndroidFD_", "struct_s_l_data_locator___android_f_d__.html", "struct_s_l_data_locator___android_f_d__" ],
    [ "SLDataLocator_AndroidSimpleBufferQueue", "struct_s_l_data_locator___android_simple_buffer_queue.html", "struct_s_l_data_locator___android_simple_buffer_queue" ]
];